/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import beans.Personagens;
import beans.Usuarios;
import dao.PersonagensJpaController;
import dao.UsuariosJpaController;
import emf.Emf;
import javax.swing.JOptionPane;

/**
 *
 * @author José Ângelo
 */
public class FormPerfil extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPerfil.class.getName());
    
    private Usuarios usr;
    private UsuariosJpaController userDAO;
    private PersonagensJpaController personagemDAO;
    private Personagens p;
    

    /**
     * Creates new form FormPerfil
     */
    public FormPerfil() {
        initComponents();
    }
    
    public FormPerfil(Usuarios usr) {
        initComponents();
        
        this.usr = usr;
        this.personagemDAO = new PersonagensJpaController(Emf.getEmf());
        this.userDAO = new UsuariosJpaController(Emf.getEmf());
        this.p = personagemDAO.findPersonagens(usr.getIdUsuario());
        
        System.out.println(usr.getIdUsuario());
        
        setOverall();
    }
    
    public void validarCompra(){
        if (usr.getMoedas() < p.getPreco()){
            btnAgilidade.setVisible(false);
            btnEnergia.setVisible(false);
            btnFoco.setVisible(false);
            btnInteligendia.setVisible(false);
        }
    }

    public void setOverall(){
        validarCompra();
        lblMoeda.setText(String.valueOf(usr.getMoedas()));
        
        lblFoc.setText(String.valueOf(p.getFoco()));
        lblAgilidade.setText(String.valueOf(p.getAgilidade()));
        lblEnergia.setText(String.valueOf(p.getEnergia()));
        lblInteligencia.setText(String.valueOf(p.getInteligencia()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        lblAgilidade = new javax.swing.JLabel();
        lblEnergia = new javax.swing.JLabel();
        lblInteligencia = new javax.swing.JLabel();
        lblFoc = new javax.swing.JLabel();
        btnFoco = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblMoeda = new javax.swing.JLabel();
        btnAgilidade = new javax.swing.JButton();
        btnInteligendia = new javax.swing.JButton();
        btnEnergia = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perfil");

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblAgilidade.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        lblAgilidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgilidade.setText("0");

        lblEnergia.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        lblEnergia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnergia.setText("0");

        lblInteligencia.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        lblInteligencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInteligencia.setText("0");

        lblFoc.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        lblFoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoc.setText("0");

        btnFoco.setText("+");
        btnFoco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFocoActionPerformed(evt);
            }
        });

        jLabel9.setText("TOTAL DE MOEDAS:");

        lblMoeda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMoeda.setText("\"Moedas\"");

        btnAgilidade.setText("+");
        btnAgilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgilidadeActionPerformed(evt);
            }
        });

        btnInteligendia.setText("+");
        btnInteligendia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInteligendiaActionPerformed(evt);
            }
        });

        btnEnergia.setText("+");
        btnEnergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnergiaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Foco:");

        jLabel2.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Agilidade:");

        jLabel3.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Inteligência:");

        jLabel4.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Energia:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMoeda))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblInteligencia, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnInteligendia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFoc, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFoco, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAgilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(jLabel9)
                    .addComponent(lblMoeda))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFoco, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFoc))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAgilidade)
                            .addComponent(btnAgilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInteligencia)
                            .addComponent(btnInteligendia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEnergia)
                            .addComponent(btnEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        Usuarios user = userDAO.findUsuarios(usr.getIdUsuario());

        FormTarefas tarefas = new FormTarefas(user);
        tarefas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnFocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFocoActionPerformed
        try {
            int total = p.getFoco()+1;
            p.setFoco(total);
            int moeda = usr.getMoedas() - p.getPreco();
            usr.setMoedas(moeda);

            personagemDAO.edit(p);
            userDAO.edit(usr);
            
            setOverall();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);

        }       

    }//GEN-LAST:event_btnFocoActionPerformed

    private void btnAgilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgilidadeActionPerformed
        try {
            int total = p.getAgilidade()+1;
            p.setAgilidade(total);
                        int moeda = usr.getMoedas() - p.getPreco();
            usr.setMoedas(moeda);

            personagemDAO.edit(p);
            userDAO.edit(usr);
            
            setOverall();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAgilidadeActionPerformed

    private void btnInteligendiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInteligendiaActionPerformed
        try {
            int total = p.getInteligencia()+1;
            p.setInteligencia(total);
            int moeda = usr.getMoedas() - p.getPreco();
            usr.setMoedas(moeda);

            personagemDAO.edit(p);
            userDAO.edit(usr);
            
            setOverall();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_btnInteligendiaActionPerformed

    private void btnEnergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnergiaActionPerformed
        try {
            int total = p.getEnergia()+1;
            p.setEnergia(total);
            int moeda = usr.getMoedas() - p.getPreco();
            usr.setMoedas(moeda);

            personagemDAO.edit(p);
            userDAO.edit(usr);
            
            setOverall();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_btnEnergiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPerfil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgilidade;
    private javax.swing.JButton btnEnergia;
    private javax.swing.JButton btnFoco;
    private javax.swing.JButton btnInteligendia;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAgilidade;
    private javax.swing.JLabel lblEnergia;
    private javax.swing.JLabel lblFoc;
    private javax.swing.JLabel lblInteligencia;
    private javax.swing.JLabel lblMoeda;
    // End of variables declaration//GEN-END:variables
}
