/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import beans.Usuarios;
import beans.Inventario;
import beans.ItensLoja;
import dao.InventarioJpaController;
import dao.ItensLojaJpaController;
import dao.UsuariosJpaController;
import emf.Emf;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class FormLoja extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormLoja.class.getName());

    private Usuarios usr;
    private UsuariosJpaController usuarioDAO;
    private ItensLojaJpaController lojaDAO;
    private InventarioJpaController inventarioDAO;

    /**
     * Creates new form FormLoja
     */
    public FormLoja() {
        initComponents();
    }
    
    public FormLoja(Usuarios usr) {
        initComponents();
        
        this.usr = usr; 
        this.usuarioDAO = new UsuariosJpaController(Emf.getEmf()); 
        
        this.usuarioDAO = new UsuariosJpaController(Emf.getEmf());
        this.lojaDAO = new ItensLojaJpaController(Emf.getEmf());
        this.inventarioDAO = new InventarioJpaController(Emf.getEmf());

        preenchertabela();
    }
    
    private void preenchertabela() {
        try {
            var em = Emf.getEmf().createEntityManager();

            String jpql = "SELECT i FROM ItensLoja i WHERE i.idLoja NOT IN "
                    + "(SELECT inv.itemId.idLoja FROM Inventario inv WHERE inv.usuarioId.idUsuario = :usuarioId)";

            List<beans.ItensLoja> itensDisponiveis = em.createQuery(jpql, beans.ItensLoja.class)
                    .setParameter("usuarioId", usr.getIdUsuario())
                    .getResultList();

            DefaultTableModel tabela = new DefaultTableModel();
            tabela.setColumnIdentifiers(new String[]{"ID", "Nome", "Descrição", "Preço"});

            for (beans.ItensLoja item : itensDisponiveis) {
                tabela.addRow(new Object[]{
                    item.getIdLoja(),
                    item.getNome(),
                    item.getDescricao(),
                    item.getPreco()
                });
            }
            tblLoja.setModel(tabela);
            lblMoeda.setText(String.valueOf(usr.getMoedas()));

            em.close();

        } catch (Exception e) {
            logger.severe("Erro ao preencher tabela: " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Erro ao carregar itens da loja.");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoja = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblMoeda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblLoja.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        tblLoja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "DESCROÇÃO", "PREÇO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLoja);

        btnVoltar.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnComprar.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel2.setText("TOTAL DE MOEDAS:");

        lblMoeda.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        lblMoeda.setText("moeda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnComprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblMoeda, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblMoeda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        Usuarios user = usuarioDAO.findUsuarios(usr.getIdUsuario());
        
        FormTarefas tarefas = new FormTarefas(user);
        tarefas.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        int linha = tblLoja.getSelectedRow();
        
        if (linha == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um item para comprar.");
            return;
        }

        int preco = Integer.parseInt(tblLoja.getValueAt(linha, 3).toString());
        int idItem = Integer.parseInt(tblLoja.getValueAt(linha, 0).toString());

        if (usr.getMoedas() < preco) {
            JOptionPane.showMessageDialog(null, "Você não tem moedas suficientes, faça suas tarefas!");
            return;
        }

        try {
            ItensLoja item = lojaDAO.findItensLoja(idItem);

            usr = usuarioDAO.findUsuarios(usr.getIdUsuario());
            usr.setMoedas(usr.getMoedas() - preco);
            usuarioDAO.edit(usr);
            
            Inventario i = new Inventario();
            
            i.setItemId(item);
            i.setUsuarioId(usr);
         

            inventarioDAO.create(i);

            JOptionPane.showMessageDialog(null, "Item comprado com sucesso!");
            preenchertabela();
        } catch (Exception e) {
            logger.severe("Erro na compra: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao realizar a compra");
        }
    }//GEN-LAST:event_btnComprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormLoja().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMoeda;
    private javax.swing.JTable tblLoja;
    // End of variables declaration//GEN-END:variables
}
