/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import beans.Tarefas;
import beans.Usuarios;
import dao.TarefasJpaController;
import emf.Emf;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormTarefas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTarefas.class.getName());

    private Usuarios usr;
    private TarefasJpaController tarefaDAO; 
    
    
    public FormTarefas() {
        initComponents();   
        preenchertabela();
    }
    
    public FormTarefas(Usuarios usr) {
        initComponents();
        this.usr = usr;
        this.tarefaDAO = new TarefasJpaController(Emf.getEmf());
    }

        private void preenchertabela(){
        DefaultTableModel tabela = (DefaultTableModel) tblTarefas.getModel();
        tabela.setNumRows(0);
        
        try {
            List<Tarefas> lista = this.tarefaDAO.ExibeTarefasAFazer(usr.getIdUsuario());
            
            for(Tarefas t : lista){
                Object[] nvLinha = new Object[]{
                    t.getDescricao(),
                    t.getDificuldade(),
                    t.getRecompensa()
                };
                tabela.addRow(nvLinha);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTarefas = new javax.swing.JTable();
        btnFinalizarTarefa = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniTarefas = new javax.swing.JMenuItem();
        mniGerenciarTarefas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniLoja = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mniInventario = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mniPerfil = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tarefas");

        tblTarefas.setFont(new java.awt.Font("Mongolian Baiti", 1, 14)); // NOI18N
        tblTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tarefa", "Dificuldade", "Recompensa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTarefas.setToolTipText("");
        jScrollPane1.setViewportView(tblTarefas);

        btnFinalizarTarefa.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        btnFinalizarTarefa.setText("Concluir Tarefa");
        btnFinalizarTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarTarefaActionPerformed(evt);
            }
        });

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1.setText("Tarefas");

        mniTarefas.setText("Tarefas");
        mniTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTarefasActionPerformed(evt);
            }
        });
        jMenu1.add(mniTarefas);

        mniGerenciarTarefas.setText("Gerenciar Tarefas");
        mniGerenciarTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGerenciarTarefasActionPerformed(evt);
            }
        });
        jMenu1.add(mniGerenciarTarefas);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Loja");

        mniLoja.setText("Loja");
        jMenu2.add(mniLoja);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Inventario");

        mniInventario.setText("Inventario");
        jMenu3.add(mniInventario);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Perfil");

        mniPerfil.setText("Perfil");
        jMenu4.add(mniPerfil);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinalizarTarefa))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFinalizarTarefa)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTarefasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniTarefasActionPerformed

    private void btnFinalizarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarTarefaActionPerformed
        System.out.println(usr);
    }//GEN-LAST:event_btnFinalizarTarefaActionPerformed

    private void mniGerenciarTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGerenciarTarefasActionPerformed
        FormGerenciarTarefas gerenciar = new FormGerenciarTarefas(usr);
        gerenciar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mniGerenciarTarefasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormTarefas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizarTarefa;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mniGerenciarTarefas;
    private javax.swing.JMenuItem mniInventario;
    private javax.swing.JMenuItem mniLoja;
    private javax.swing.JMenuItem mniPerfil;
    private javax.swing.JMenuItem mniTarefas;
    private javax.swing.JTable tblTarefas;
    // End of variables declaration//GEN-END:variables
}
